### ISSUE TITLE
Loading app with invalid refresh token leads to crash 

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/web#169]
Reported by @jspaleta 

1. create a user with a password
1. login to web-ui with that user
1. disable user with sensuctl
1. refresh web-ui
1. crash

![image](https://user-images.githubusercontent.com/194892/61240203-80d2ae80-a6f5-11e9-9238-78b869b54dc8.png)

**Comment by calebhailey** [comment]
I wonder if this is the same behavior I have observed upon upgrading in my dev environment. If I have logged in to a `localhost` sensu-backend (e.g. running as a Docker container), and I nuke that backend (including the etcd data) and spin up a fresh backend w/ new etcd, and try to login... :boom: error. If I clear my cookies then all is well again. Would this create the same scenario in that my browser has a refresh token that is not valid for the new/fresh backend, thus leading to error city?

**Comment by jspaleta** [comment]
so i'm pretty sure there is related to how the application caches auth tokens in the browser data store.
In firefox I was able to delete the cached data for localhost server and fixed the problem.

I keep running into this in different context.. but fundamentally i think its the cached credentials. There isn't a fail over gracefully to a relogin page if the cached information is incorrect.

**Comment by jamesdphillips** [comment]
> I wonder if this is the same behavior I have observed upon upgrading in my dev environment. If I have logged in to a localhost sensu-backend (e.g. running as a Docker container), and I nuke that backend (including the etcd data) and spin up a fresh backend w/ new etcd, and try to login... 💥 error. If I clear my cookies then all is well again. Would this create the same scenario in that my browser has a refresh token that is not valid for the new/fresh backend, thus leading to error city?

Your refresh token stored in localStorage would no longer be valid, so yes, this is very likely related.

> I keep running into this in different contexts.. while working with configuring users...but fundamentally i think its the cached credentials bug. There isn't a fail over gracefully to a relogin page if the cached information in the browser is incorrect.

I wonder if we should add the option to clear localStorage when you encounter the exception modal? 🤔
