### ISSUE TITLE
Add option to clear state when exception modal is encountered

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/web#173]
In some rare cases a crash may occur as a product of the data in `localStorage` (or possibly a value encoded in the URL.) In these cases refreshing the page is unlikely to fix the issue and they are likely are stuck in a broken state until they clear `localStorage` manually.

To improve the experience, it would be nice to add an option to the exception modal to clear state and take the user back to the login view.

**Comment by annaplotkin** [comment]
Add option to clear local storage cache.
