### ISSUE TITLE
Wrong index display on pagination widget

### ISSUE THREAD

**Issue by ccressent** [sensu/web#187]
## Expected Behavior

The correct item range is displayed

## Current Behavior

An incorrect item range is displayed

## Steps to Reproduce

1. Go to the events page
2. Select 5 rows per page at the bottom
3. Skip ahead a few pages
4. Select 100 or 200 rows per page
5. Observe the widget claiming something like `101-72 of 72`

## Context

Noticed during 5.12 QA

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.12-rc1
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):
* Browser used: Chromium

**Comment by ccressent** [comment]
Still happening as of 5.18.

**Comment by agm650** [comment]
For what it worth this issue is apparently fixed with the latest webui (running it from sources, or with the 6.2.2 backend).

**Comment by calebhailey** [comment]
Thanks @agm650 🙌
