### ISSUE TITLE
Confirmation dialog for check publishing says the wrong thing

### ISSUE THREAD

**Issue by echlebek** [sensu/web#203]
## Expected Behavior
When a check's published state is changed from false to true, the confirmation dialog says "check published"

## Current Behavior
The confirmation dialog says "check unpublished"

## Possible Solution
???

## Steps to Reproduce
Navigate to a check info page, un-publish the check, and then publish it again. Observe that the notifications both say "Unpublish".

**Comment by jamesdphillips** [comment]
Confirmed that this has indeed been fixed.
