### ISSUE TITLE
Unexpected Error: "a.__setDigit is not a function"

### ISSUE THREAD

**Issue by derekgroh** [sensu/web#225]
## Expected Behavior
Dashboard continues to display the event page without crashing.

## Current Behavior
Dashboard crashes displaying the error with the output: 
`value@http://<REDACTED>/static/js/lib_a7e6.js:10:209184
value@http://<REDACTED>/static/js/lib_a7e6.js:10:201765
nextInterval@http://<REDACTED>/static/js/app_a5eb.js:1:202797
EventDetailsCheckHistory@http://<REDACTED>/static/js/app_a5eb.js:1:202693
hg@http://<REDACTED>/static/js/vendor_89b2.js:152:53108
Mg@http://<REDACTED>/static/js/vendor_89b2.js:152:59913
Tg@http://<REDACTED>/static/js/vendor_89b2.js:152:66598
bi@http://<REDACTED>/static/js/vendor_89b2.js:152:90700
ci@http://<REDACTED>/static/js/vendor_89b2.js:152:91084
Di@http://<REDACTED>/static/js/vendor_89b2.js:152:97974
Yh@http://<REDACTED>/static/js/vendor_89b2.js:152:97354
Xh@http://<REDACTED>/static/js/vendor_89b2.js:152:96375
qf@http://<REDACTED>/static/js/vendor_89b2.js:152:95246
wg@http://<REDACTED>/static/js/vendor_89b2.js:152:56094
next@http://<REDACTED>/static/js/app_a5eb.js:1:969902
notifySubscription@http://<REDACTED>/static/js/vendor_89b2.js:105:26225
onNotify@http://<REDACTED>/static/js/vendor_89b2.js:105:26843
next@http://<REDACTED>/static/js/vendor_89b2.js:105:27657
iterateObserversSafely/<@http://<REDACTED>/static/js/vendor_89b2.js:90:195864
iterateObserversSafely@http://<REDACTED>/static/js/vendor_89b2.js:90:195835
next@http://<REDACTED>/static/js/vendor_89b2.js:90:195293
invoke@http://<REDACTED>/static/js/vendor_89b2.js:90:209833
dMq0/</O</QueryManager.prototype.queryListenerForObserver/<@http://<REDACTED>/static/js/vendor_89b2.js:90:211039
dMq0/</O</QueryManager.prototype.broadcastQueries/</<@http://<REDACTED>/static/js/vendor_89b2.js:90:216828
dMq0/</O</QueryManager.prototype.broadcastQueries/<@http://<REDACTED>/static/js/vendor_89b2.js:90:216793
dMq0/</O</QueryManager.prototype.broadcastQueries@http://<REDACTED>/static/js/vendor_89b2.js:90:216743
dMq0/</O</QueryManager.prototype.fetchQuery/</<@http://<REDACTED>/static/js/vendor_89b2.js:90:208708
step@http://<REDACTED>/static/js/vendor_89b2.js:105:2607
verb/<@http://<REDACTED>/static/js/vendor_89b2.js:105:1929
__awaiter/<@http://<REDACTED>/static/js/vendor_89b2.js:105:1605
o/<[7]</n.exports/n.prototype._execute@http://<REDACTED>/static/js/vendor_89b2.js:90:103853
o/<[15]</n.exports/Promise.prototype._resolveFromExecutor@http://<REDACTED>/static/js/vendor_89b2.js:90:128383
Promise@http://<REDACTED>/static/js/vendor_89b2.js:90:121199
__awaiter@http://<REDACTED>/static/js/vendor_89b2.js:105:1366
dMq0/</O</QueryManager.prototype.fetchQuery@http://<REDACTED>/static/js/vendor_89b2.js:90:207574
u@http://<REDACTED>/static/js/vendor_89b2.js:90:220354`

## Steps to Reproduce (for bugs)
1. Setup backend and agents
2. Create checks, filters, handlers
3. Begin monitoring (Isolated to one check and email handler)
4. Dashboard crash, no apparent impact to events via sensuctl, no action required for crash.

## Context
Unusable WebUI as a dashboard for monitoring health of environment.
**Browser Stack Trace:**

at `value` (/static/js/lib_a7e6.js:10)
at `value` (/static/js/lib_a7e6.js:10)
at `nextInterval` (/static/js/app_a5eb.js:1)
at `EventDetailsCheckHistory` (/static/js/app_a5eb.js:1)
at `hg` (/static/js/vendor_89b2.js:152)
at `Mg` (/static/js/vendor_89b2.js:152)
at `Tg` (/static/js/vendor_89b2.js:152)
at `bi` (/static/js/vendor_89b2.js:152)
at `ci` (/static/js/vendor_89b2.js:152)
at `Di` (/static/js/vendor_89b2.js:152)
at `Yh` (/static/js/vendor_89b2.js:152)
at `Xh` (/static/js/vendor_89b2.js:152)
at `qf` (/static/js/vendor_89b2.js:152)
at `wg` (/static/js/vendor_89b2.js:152)
at `useCurrentDate/</t<` (/static/js/app_a5eb.js:1)

React Component Stack:

```
in EventDetailsCheckHistory
in div
in ForwardRef
in ForwardRef(WithStyles)
in div
in ForwardRef
in ForwardRef(WithStyles)
in EventDetailsContainer
in div
in div
in div
in AppLayout
in ForwardRef(WithStyles)
in div
in div
in Loader
in ForwardRef(WithStyles)
in AppLayout
in EventDetailsViewContent
in EventDetailsViewContents
in EventDetailsViewWrapper
in Route
in Switch
in NavigationProvider
in Query
in Route
in NamespaceRoute
in Switch
in Route
in ConditionalRoute
in AuthenticatedRoute
in Query
in Apollo(AuthenticatedRoute)
in Switch
in ThemeProvider
in ThemeProvider
in AppThemeProvider
in Provider
in ApolloProvider
in Provider
in AppRoot
in Route
in withRouter(AppRoot)
in Router
in BrowserRouter
in ErrorBoundary
```

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
  sensu/web revision: `5c59069` (5.15.0)
* Installation method (packages, binaries, docker etc.): yum
* Operating System and version: CentOS 7.7

**Comment by jamesdphillips** [comment]
Closed by #237
