### ISSUE TITLE
Problem Implementing OIDC with OKTA

### ISSUE THREAD

**Issue by bradpoulton** [sensu/web#232]
I am attempting to setup Sensu dashboard with OKTA OIDC auth. After setting up sensu for OKTA auth, i got this error. 

# Expected Behavior
No stack trace when logging into Sensu with OIDC auth method (OKTA).

# Current Behavior
Got a stack trace.

# Steps to Reproduce (for bugs)
Setup OKTA OIDC auth following steps here: https://docs.sensu.io/sensu-go/latest/installation/auth/#okta

Sensu config:
---
    type: oidc
    api_version: authentication/v2
    metadata:
      name: okta
    spec:
      additional_scopes:
      - groups
      - email
      client_id: client_id
      client_secret: client_secret
      redirect_uri: https://sensu.mydomain.local:8080/api/enterprise/authentication/v2/oidc/callback
      server: https://myokta.okta.com
      groups_claim: groups
      groups_prefix: 'okta'
      username_claim: email
      username_prefix: 'okta'

# Context
Encountered during setting up OKTA OIDC auth.

# Browser Stack Trace:

Error: GraphQL error: no claims found in the request context
    at new ApolloError (https://sensu.mydomain.local:8000/static/js/vendor_89b2.js:90:188247)
    at https://sensu.mydomain.local:8000/static/js/vendor_89b2.js:90:210401
    at https://sensu.mydomain.local:8000/static/js/vendor_89b2.js:90:216828
    at Set.forEach (<anonymous>)
    at https://sensu.mydomain.local:8000/static/js/vendor_89b2.js:90:216805
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (https://sensu.mydomain.local:8000/static/js/vendor_89b2.js:90:216756)
    at https://sensu.mydomain.local:8000/static/js/vendor_89b2.js:90:218737
    at Object.next (https://sensu.mydomain.local:8000/static/js/vendor_89b2.js:105:28920)
    at notifySubscription (https://sensu.mydomain.local:8000/static/js/vendor_89b2.js:105:26227)
    at onNotify (https://sensu.mydomain.local:8000/static/js/vendor_89b2.js:105:26843)
    at SubscriptionObserver.next (https://sensu.mydomain.local:8000/static/js/vendor_89b2.js:105:27657)
    at https://sensu.mydomain.local:8000/static/js/vendor_89b2.js:90:203940
    at Set.forEach (<anonymous>)
    at Object.next (https://sensu.mydomain.local:8000/static/js/vendor_89b2.js:90:203903)
    at notifySubscription (https://sensu.mydomain.local:8000/static/js/vendor_89b2.js:105:26227)

# Your Environment
Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensu-backend/sensu web
sensu/web revision: 5.16.1
web revision 499558f
Installation method (packages, binaries, docker etc.): rpm packages 
Operating System and version (e.g. Ubuntu 14.04): redhat 7.7
web is running on port 8000 (not using default port)
API is running on port 8080

**Comment by bradpoulton** [comment]
I am also seeing this error:
`{"message":"oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"The authorization code is invalid or has expired.\"}","code":0}`

**Comment by bradpoulton** [comment]
Okta Logs

![image](https://user-images.githubusercontent.com/1007046/71927656-2faaf100-3153-11ea-9093-32f95a7a314c.png)

**Comment by palourde** [comment]
Hi @bradpoulton 

Thanks for this detailed bug report. To help us better identify the problem, could you attempt to authenticate against Okta using the `sensuctl login oidc` command and provide us the output and all related logs?

Thanks

**Comment by bradpoulton** [comment]
@palourde Thank you, here are the results. Please let me know if you need additional logs. 

$ sensuctl login oidc
Launching browser to complete the login via your OIDC provider at following URL:

	https://mysensu.example.local:8080/api/enterprise/authentication/v2/oidc/authorize?callback=http%3A%2F%2Flocalhost%3A8000%2Fcallback

You may also manually open this URL. Waiting for callback...


From the browser:

{"message":"oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"The authorization code is invalid or has expired.\"}","code":0}

From Okta:

OIDC token request
failure : invalid_authorization_code
failed app.oauth2.token.grant

**Comment by calebhailey** [comment]
Related: https://discourse.sensu.io/t/problem-implementing-oidc-with-okta/1568

**Comment by jamesdphillips** [comment]
@bradpoulton there was a bug fix in v5.17.1 that may have resolved this behaviour. If you're still trying to use OTKA would you mind trying again, I would like to close out this ticket if your issue is resolved.

Thanks!

**Comment by jamesdphillips** [comment]
I think this is safe to close.

**Comment by bradpoulton** [comment]
Hello, Sorry for reopening this ticket, but i was able to attempt to setup OKTA OIDC again.
