### ISSUE TITLE
Unexpected Error: "Cannot read property 'name' of null"

### ISSUE THREAD

**Issue by TheMaskMaker** [sensu/web#235]
## Expected Behavior
I was just running some default checks, or trying to. Sensu auto-created this issue.

## Current Behavior
This error

## Steps to Reproduce (for bugs)
        - name: Check executing command every 30 seconds
          check:
            name: check
            auth:
              url: "XXXXXXXXXXXXXXXXXXXXXXXX"
            command: check-cpu.sh -w 75 -c 90
            subscriptions:
              - linux
            interval: 30
            publish: yes
            state: absent
## Context

**Browser Stack Trace:**

at `DeleteCheckAction.render` (/static/js/app_fe52.js:1)
at `Qg` (/static/js/vendor_89b2.js:152)
at `Og` (/static/js/vendor_89b2.js:152)
at `Tg` (/static/js/vendor_89b2.js:152)
at `bi` (/static/js/vendor_89b2.js:152)
at `ci` (/static/js/vendor_89b2.js:152)
at `Di` (/static/js/vendor_89b2.js:152)
at `Yh` (/static/js/vendor_89b2.js:152)
at `Xh` (/static/js/vendor_89b2.js:152)
at `qf` (/static/js/vendor_89b2.js:152)
at `wg` (/static/js/vendor_89b2.js:152)
at `Object.next` (/static/js/app_fe52.js:1)
at `notifySubscription` (/static/js/vendor_89b2.js:105)
at `onNotify` (/static/js/vendor_89b2.js:105)
at `SubscriptionObserver.next` (/static/js/vendor_89b2.js:105)

React Component Stack:

```
in DeleteCheckAction
in Route
in withRouter(DeleteCheckAction)
in p
in withApollo(withRouter(DeleteCheckAction))
in div
in ToolbarMenu.Item
in div
in ToolbarMenu.Partitioner
in ToolbarMenu
in div
in Toolbar
in ForwardRef(WithStyles)
in CheckDetailsToolbar
in div
in Content
in ForwardRef(WithStyles)
in CheckDetailsContainer
in div
in div
in div
in AppLayout
in ForwardRef(WithStyles)
in div
in div
in Loader
in ForwardRef(WithStyles)
in AppLayout
in CheckDetailsViewContent
in CheckDetailsViewContents
in CheckDetailsViewWrapper
in Route
in Switch
in NavigationProvider
in Query
in Route
in NamespaceRoute
in Switch
in Route
in ConditionalRoute
in AuthenticatedRoute
in Query
in Apollo(AuthenticatedRoute)
in Switch
in ThemeProvider
in ThemeProvider
in AppThemeProvider
in ApolloProvider
in Provider
in AppRoot
in Route
in withRouter(AppRoot)
in Router
in BrowserRouter
in ErrorBoundary
```

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
  sensu/web revision: `499558f`
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

also sensu-monitoring-2.2.0-1 was used with backend v1.1.1

**Comment by jamesdphillips** [comment]
Thanks for the detailed issue. This should be fixed in the upcoming release v6.1.0.
