### ISSUE TITLE
WebGUI: publishing and unpublishing Checks alwas show the same notification on the GUI

### ISSUE THREAD

**Issue by marcseguin** [sensu/web#243]
When I publish oder unpublish a check I always get the some notification on the right down corner: "Unpublished <check-name>". It's more a cosmetic issue as the function itself look OK.

![image](https://user-images.githubusercontent.com/5563153/61724411-33e27e00-ad6e-11e9-8dca-95aa434ae896.png)

## Expected Behavior
Depending whether I publish or unpublish a check the shown notification shall be refer to the executed action.

## Current Behavior
Independing whether I publish or unpublish a check the shown notification refers always to an unpublishing action.

## Steps to Reproduce (for bugs)
1. Unpublish and Publish a check

## Your Environment
Version 5.11 of Sensu Go, CentOS 7

**Comment by jamesdphillips** [comment]
Re-tested in the latest release and it appears as if this was fixed.
