### ISSUE TITLE
Unexpected Error: "Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "

### ISSUE THREAD

**Issue by nilroy** [sensu/web#261]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

**Browser Stack Trace:**

at `ba` (/static/js/vendor_bcb1.js:152)
at `x` (/static/js/vendor_bcb1.js:152)
at `Ye` (/static/js/vendor_bcb1.js:152)
at `undefined` (/static/js/vendor_bcb1.js:152)
at `S` (/static/js/vendor_bcb1.js:152)
at `Qg` (/static/js/vendor_bcb1.js:152)
at `Og` (/static/js/vendor_bcb1.js:152)
at `Tg` (/static/js/vendor_bcb1.js:152)
at `bi` (/static/js/vendor_bcb1.js:152)
at `ci` (/static/js/vendor_bcb1.js:152)
at `Di` (/static/js/vendor_bcb1.js:152)
at `Yh` (/static/js/vendor_bcb1.js:152)
at `Xh` (/static/js/vendor_bcb1.js:152)
at `qf` (/static/js/vendor_bcb1.js:152)
at `wg` (/static/js/vendor_bcb1.js:152)

React Component Stack:

```
in Annotation
in td
in ForwardRef(Typography)
in ForwardRef(WithStyles)
in DictionaryValue
in ForwardRef(WithStyles)
in StyledComponent
in LabelsAnnotationsCell.Value
in tr
in DictionaryEntry
in tbody
in table
in Dictionary
in ForwardRef(WithStyles)
in div
in ForwardRef
in ForwardRef(WithStyles)
in div
in ForwardRef
in ForwardRef(WithStyles)
in LabelsAnnotationsCell
in div
in ForwardRef(CardContent)
in ForwardRef(WithStyles)
in div
in ForwardRef(Paper)
in ForwardRef(WithStyles)
in ForwardRef(Card)
in ForwardRef(WithStyles)
in EntityDetailsInformation
in div
in ForwardRef
in ForwardRef(WithStyles)
in div
in ForwardRef
in ForwardRef(WithStyles)
in EntityDetailsContainer
in div
in div
in div
in AppLayout
in ForwardRef(WithStyles)
in div
in div
in Loader
in ForwardRef(WithStyles)
in AppLayout
in EntityDetailsViewContent
in EntityDetailsView
in Route
in Switch
in NavigationProvider
in Query
in Route
in NamespaceRoute
in Switch
in Route
in ConditionalRoute
in AuthenticatedRoute
in Query
in Apollo(AuthenticatedRoute)
in Switch
in ThemeProvider
in ThemeProvider
in AppThemeProvider
in Provider
in ApolloProvider
in Provider
in AppRoot
in Route
in withRouter(AppRoot)
in Router
in BrowserRouter
in ErrorBoundary
```

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
  sensu/web revision: `ce8990b`
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by daswars** [comment]
I have the same problem with 5.18.0 and and 5.18.1 
With 5.17.2 i have no problems.

**Comment by jgrasser** [comment]
Same here, open source sensu-go built on the v5.181 tag. Running sensu/web revision ce8990b.
I wasn't able to pull more information than what nilroy posted above.

@nilroy was this issue resolved? if not, could you please move this to the web repo.

**Comment by jgrasser** [comment]
Ah, this was reported on sensu/web. See https://github.com/sensu/web/issues/271
