### ISSUE TITLE
Cross Origin error when rendering image

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/web#273]
<img width="630" alt="Screen Shot 2020-03-19 at 9 49 26 AM" src="https://user-images.githubusercontent.com/194892/77117057-78eaad00-69ee-11ea-82fc-c5625dc9fb0e.png">

## Expected Behavior

No crash.

## Current Behavior

Crash!

## Possible Solution

We likely just need to ensure any exceptions are caught here: https://github.com/sensu/web/blob/master/src/lib/component/partial/KeyValueChip/KeyValueChip.js#L101-L107.

## Steps to Reproduce

Have a label or annotation with an image or URL pointing to a remote server that doesn't not allow cross origin requests, eg. use `https://www.duckduckgo.com`. 

## Your Environment

Unreleased.

**Comment by dabria** [comment]
Closed by https://github.com/sensu/web/pull/278
