### ISSUE TITLE
Cannot see who I'm connected as in dashboard

### ISSUE THREAD

**Issue by ccressent** [sensu/web#31]
## Expected Behavior

I can see who I'm connected as in the dashboard.

## Current Behavior

The user who is currently connected is not displayed anywhere.

## Context

While testing RBAC, I had several independent browser windows connected as different users, but couldn't easily tell which window was which user.

**Comment by portertech** [comment]
Closed by https://github.com/sensu/sensu-enterprise-go/issues/639

**Comment by portertech** [comment]
Actually closed by https://github.com/sensu/sensu-enterprise-go/issues/639 :tada:
