### ISSUE TITLE
Sort button in Web UI doesn't work after first sort (Chrome)

### ISSUE THREAD

**Issue by amccrea** [sensu/web#331]
When in the events tab of the web UI, I can sort by newest/oldest/severity/lastOK, and that works. But when I try to sort by something else, nothing happens. 

https://<sensu.backend>:3000/c/~/n/<namespace1>/events

Click sort by newest. 

https://<sensu.backend>:3000/c/~/n/<namespace1>/events?order=NEWEST

Click sort by severity. 

https://<sensu.backend>:3000/c/~/n/<namespace1>/events?order=NEWEST

URL doesn't change, nor does the sorting order of events. I can provide a video of the issue if needed. 

Other filters (entity, check, etc) work fine -- they create a filter in the filter box and that changes when clicking anything in their respective drop down menus. Sort does not create anything in the filter box. 

Sensu backend 5.21, set up using sensu-puppet
CentOS7
Browser: Chrome 84.0.4147.89

**Comment by jamesdphillips** [comment]
The fix for this issue is available in `>= v6.0` of commercial distribution and `>= v1.0.1` of the open source distribution.

Fixed with #327.
