### ISSUE TITLE
Entity, Check and Subscription Dropdown menus (in the Entities and Events tabs) only show the first 50 items

### ISSUE THREAD

**Issue by amccrea** [sensu/web#335]
Entity, Check dropdowns (in Events tab) and Subscription dropdown menu (in Entity tab) only display the first 50 items. 

## Expected Behavior
Since our environments/namespaces are large, with several hundred hosts, checks and >50 subscriptions, we expect the dropdown to contain every entity and check. 

## Current Behavior
Right now, I only see 50 hosts in the Entity dropdown menu, for instance. 

## Possible Solution
Please show all items in the dropdown, or better yet, make it configurable. 

## Steps to Reproduce
1. Log into the Sensu Web UI
2. Click on Events in the left side bar
3. Next to sort, status, etc buttons, click "Entity"
4. The entity I'm looking for is not there because it tops out at 50 entities.

Here the dropdown ends at the hosts that start with "R". (They are added to sensu by puppet in alphabetical order and the host I need starts with "L", for instance). 
<img width="1430" alt="Screen Shot 2020-08-07 at 10 44 51 AM" src="https://user-images.githubusercontent.com/5014001/89673592-7acce400-d89b-11ea-80f2-f160f75e515d.png">

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5:20
* Installation method (packages, binaries, docker etc.): rpm
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7
* Browser used: Chrome

**Comment by calebhailey** [comment]
I wonder if our upcoming search improvements will satisfy the UX issue here. Is it actually helpful to scroll through hundreds of resources in a drop-down vs using the new & improved search + auto-complete?

**Comment by amccrea** [comment]
> I wonder if our upcoming search improvements will satisfy the UX issue here. Is it actually helpful to scroll through hundreds of resources in a drop-down vs using the new & improved search + auto-complete?

You are absolutely right...I have been using the drop box mostly as a replacement for search because it has partial auto-complete (I'd type "R" and the "R" entities would come up, saving a step from having to type "entities:" in the search bar). If the search can now do auto complete, that would be far superior and this FR could be closed. 

Thanks! Looking forward to the new UI updates! 😀
