### ISSUE TITLE
Event detail "run at" and "issued at" precision for <1min interval checks.

### ISSUE THREAD

**Issue by agoddard** [sensu/web#353]
The Event detail page only shows precision down to hours/minutes. When checks are scheduled with a short interval (e.g. every few seconds), the "issued at" and "ran at" lack precision to show this. It would be great to allow precision down to seconds in the event detail page "issued at" and "run at" fields.

**Comment by agm650** [comment]
I think I found where to update the code in order to get the second displayed in both field.
is it ok if its done like this by default? or do you need some configuration to control this behavior?
