### ISSUE TITLE
Count events like uchiwa

### ISSUE THREAD

**Issue by runningman84** [sensu/web#360]
## Feature Suggestion

I would like to have an counter how many events or broken entities are found for each level. This was a very important feature in the uchiwa gui.
It would be unfortunate if a simple count is only part of the commercial gui.

**Comment by jamesdphillips** [comment]
Due to performance constraints in the open-source offering this may lead to issues. This may be something we can add as an opt-in feature.

**Comment by runningman84** [comment]
Based on my experience in the last days it looks like sensu go does not scale as well as the old sensu stuff. :/

**Comment by portertech** [comment]
We do not currently have any plans to update the OSS web UI with an event counter (we know this does not work well with etcd).
