### ISSUE TITLE
Allow turning off "verify SSL cert" for http-proxy-middleware proxy config

### ISSUE THREAD

**Issue by thisgarryhas2rs** [sensu/web#362]
## Feature Suggestion
Allow for setting "secure: false" in the proxy config in the serve.js file. 

## Possible Implementation
Setting an environment variable "NODE_PROXY_SECURE" to false.

Update scripts/serve.js:
```
app.use(
  createProxyMiddleware(proxyPaths, {
    target: apiUrl,
    secure: process.env.NODE_PROXY_SECURE === "false" ? false : true,
    logLevel: process.env.NODE_ENV === "development" ? "silent" : "info",
  }),
);
```

## Context

In my development environment, I don't use a CA signed certificate. This will break sensu web with a "500" error when trying to authenticate on the log in page.

**Comment by thisgarryhas2rs** [comment]
Logs showing: `[HPM] Error occurred while trying to proxy request /auth from localhost:3033 to https://192.168.10.50:8080 (UNABLE_TO_VERIFY_LEAF_SIGNATURE)`

**Comment by echlebek** [comment]
Thanks for filing the issue, would you be interested in contributing a patch that implements it?

**Comment by thisgarryhas2rs** [comment]
Changes merged.
