### ISSUE TITLE
Provide a Docker Image

### ISSUE THREAD

**Issue by baer95** [sensu/web#370]
When trying to figure out how to deploy the new web dashboard, I found myself searching for a docker image and realising that there is none, and when trying to create one for my own, I thought "maybe I'm not the only one with this problem".

I think that running sensu/web inside a docker container should be fairly simple as it is a static web application that entirely uses `sensu-backend` for any state.

## Feature Suggestion

with an official docker image, it would be easy to have automatic deployments to k8s or similar managed through any config management tool like Ansible.

**Comment by portertech** [comment]
Sensu Engineering no longer works on this project and we have no plans to package it for distribution. For the officially supported web dashboard, please use the commercial distribution of Sensu Go. None of this can stop you from creating your own packaging and sharing it with the community :)

**Comment by baer95** [comment]
Thank you for your feedback!

Does that mean that sensu/web should be considered dead or deprecated?
The release notes of sensu/sensu-go [v6.0.0](https://github.com/sensu/sensu-go/blob/main/CHANGELOG.md#600---2020-08-04) suggest that sensu/web is the "new" thing:

> The web interface is now a standalone product and no longer distributed inside the sensu-backend binary. Refer to sensu/web for more.

**Comment by sekrett** [comment]
@baer95 So you did it: https://github.com/baer95/sensu-web-docker
Thank you a lot!
